support for chrome.webRequest
lucidd/scala-js-chrome pull request #34
Opened 2017-12-15 08:18 UTC by dylanowen

This adds initial support for https://developer.chrome.com/extensions/webRequest#type-BlockingResponse. I deviated from the Event and EventSource pattern used elsewhere but due to the listener function's parameters I wasn't sure what else to do. Let me know if you have any suggestions.

2018-01-22 09:56 UTC, lucidd requested changes
Hey sorry for the long delay. Thanks you very much for this contribution 👍 The PR looks good there are just some new lines missing at the end of some files. Will merge after this is fixed.

2018-01-22 09:56 UTC, lucidd commented on bindings/src/main/scala/chrome/webRequest/BlockingRequestEventSource.scala
> +}
This and a few other files are missing a new line at the end of the file.

2018-01-22 20:53 UTC, dylanowen commented
Thanks for the review, I believe I cleaned up all the missing newlines. Let me know if there is anything else.

2018-01-23 23:51 UTC, lucidd approved these changes

2018-01-23 23:53 UTC, lucidd commented
Looks fine now 👍  Thanks again for this great PR!

2018-01-23 23:53 UTC, merged